from __future__ import annotations

from pathlib import Path

import carb
import omni.usd

from ..core.safety import validate_output_path
from .aec_inspection import block_dimensions, collect_aec_inventory
from .results import tool_result


def export_idf_placeholder(output_path: str = "C:/temp/energy_model.idf") -> dict:
    allowed, result = validate_output_path(output_path)
    if not allowed:
        return tool_result(False, "No se pudo exportar el placeholder IDF.", errors=[result])
    stage = omni.usd.get_context().get_stage()
    if stage is None:
        return tool_result(False, "No hay ningun stage abierto.", errors=["No stage is currently open."])
    inventory = collect_aec_inventory(stage)
    blocks = [_block_summary(block) for block in inventory["blocks"]]
    spaces = [_space_summary(space) for space in inventory["spaces"]]
    surfaces = [_surface_summary(surface) for surface in inventory["surfaces"]]
    path = Path(result)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(_build_placeholder_idf(blocks, spaces, surfaces), encoding="utf-8")
    carb.log_info(f"[Energy Twin Agent] Wrote placeholder IDF to {path}")
    warnings = []
    if not blocks:
        warnings.append("No hay bloques AEC; el archivo solo contiene cabecera placeholder.")
    return tool_result(
        True,
        "Exportacion placeholder IDF completada.",
        {"output_path": str(path), "block_count": len(blocks), "space_count": len(spaces), "surface_count": len(surfaces)},
        warnings,
    )


def export_idf(output_path: str = "C:/temp/energy_model.idf") -> dict:
    return export_idf_placeholder(output_path)


def _build_placeholder_idf(blocks: list[dict], spaces: list[dict], surfaces: list[dict]) -> str:
    lines = [
        "! EnergyPlus IDF placeholder generated by dt.energy.agent",
        "! Source hierarchy follows custom.aec.modeling: /World/Building/Block_XX/Spaces/Space_XX/Surfaces.",
        "! This is a structured summary, not a runnable EnergyPlus model yet.",
        "",
        "Version, 24.1;",
        "",
    ]
    for block in blocks:
        lines.extend([
            f"! AEC Block: {block['path']}",
            f"! Dimensions meters: width={block['width']} depth={block['depth']} height={block['height']}",
            "",
        ])
    for space in spaces:
        lines.extend(["Zone,", f"  {space['name']};  !- Name ({space['path']})", ""])
    for surface in surfaces:
        lines.extend([
            f"! Surface: {surface['path']}",
            f"! Type={surface['surface_type']} Boundary={surface['boundary']}",
        ])
    if not blocks:
        lines.append("! No AEC blocks found.")
    return "\n".join(lines)


def _block_summary(prim) -> dict:
    dimensions = block_dimensions(prim.GetStage(), prim)
    return {
        "path": prim.GetPath().pathString,
        "width": dimensions["width"],
        "depth": dimensions["depth"],
        "height": dimensions["height"],
        "dimension_source": dimensions["source"],
    }


def _space_summary(prim) -> dict:
    return {"path": prim.GetPath().pathString, "name": _attr_value(prim, "aec:name") or prim.GetName()}


def _surface_summary(prim) -> dict:
    return {
        "path": prim.GetPath().pathString,
        "surface_type": _attr_value(prim, "aec:surfaceType"),
        "boundary": _attr_value(prim, "aec:outsideBoundaryCondition") or _attr_value(prim, "aec:thermalBoundary"),
    }


def _attr_value(prim, attr_name: str):
    attr = prim.GetAttribute(attr_name)
    if attr and attr.IsValid() and attr.HasAuthoredValueOpinion():
        return attr.Get()
    return None
